//
// Created by jakechen on 2016/4/12.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_dennishucd_FFmpegNative */

#ifndef _Included_cn_dennishucd_FFmpegNative
#define _Included_cn_dennishucd_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_dennishucd_FFmpegNative
 * Method:    avcodec_find_decoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_jake_jnicore_JniVideo_getRotate(JNIEnv *env, jobject obj, jstring path);

#ifdef __cplusplus
}
#endif
#endif

